backend:
  # name:test-repo - for testing
  # name:git-gateway - for production
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

# god bless this stackoverflow forum https://stackoverflow.com/questions/55525988/netlify-cms-how-to-store-an-array-of-objects-via-config-yml-collections

collections:
  - name: "story"

    label: "Story"
    extension: "json"
    create: true
    folder: "static/stories"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          pattern: ["^.{0,10}$", "Must have at least 20 characters"],
        }
      - { label: "Level", name: "level", widget: "number" }
      - { label: "Title Card", name: "title-card", widget: "image" }
      - label: "Authors"
        name: "authors"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - { label: "Type", name: "type", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
      - label: "Artists"
        name: "artists"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - { label: "Type", name: "type", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
      - label: "Section"
        name: "section"
        widget: "list"
        fields:
          - { label: "Media", name: "media", widget: "image" }
          - { label: "Sentence", name: "sentence", widget: "string" }
          - {
              label: "Word",
              name: "word",
              widget: "string",
              required: false,
              pattern: ["^.{0,10}$", "Must have at no more than 10 characters"],
            }
