backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "story"
    label: "Story"
    folder: "content/story"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    files:
      - label: "Page"
        name: "page"
        widget: "list"
        file: "static/pages.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "img", widget: "string" }
          - { label: "Sentence", name: "sentence", widget: "string" }
          - { label: "Word", name: "word", widget: "string" }

    # fields:
    #   - { label: "Title", name: "title", widget: "string" }
    #   - { label: "Publish Date", name: "date", widget: "datetime" }
    #   - { label: "Description", name: "description", widget: "string" }
    #   - { label: "Body", name: "body", widget: "markdown" }
