backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

# test-repo in backend > name: for testing
# git-gateway in backend > name: for production
# god bless this stackoverflow forum https://stackoverflow.com/questions/55525988/netlify-cms-how-to-store-an-array-of-objects-via-config-yml-collections

collections:
  - name: 'story'
    label: 'Story'
    create: true
    file: 'static/stories.json'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Level', name: 'level', widget: 'number' }
      - label: 'Section'
        name: 'section'
        widget: 'list'
        fields:
          - { label: 'Image', name: 'img', widget: 'string' }
          - { label: 'Sentence', name: 'sentence', widget: 'string' }
          - { label: 'Word', name: 'word', widget: 'string' }
