backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

# test-rep in backend > name: for testing
# god bless this stackoverflow forum https://stackoverflow.com/questions/55525988/netlify-cms-how-to-store-an-array-of-objects-via-config-yml-collections

collections:
  - name: "level"
    label: "Level"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    editor:
      preview: false
    files:
      - name: "story"
        label: "Story"
        create: true
        file: "static/stories.json"
        fields:
          - name: "page"
            label: "Page"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "img", widget: "string" }
              - { label: "Sentence", name: "sentence", widget: "string" }
              - { label: "Word", name: "word", widget: "string" }
