backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

# test-repo in backend > name: for testing
# git-gateway in backend > name: for production
# god bless this stackoverflow forum https://stackoverflow.com/questions/55525988/netlify-cms-how-to-store-an-array-of-objects-via-config-yml-collections

collections:
  - name: "story"
    label: "Story"
    extension: "json"
    create: true
    folder: "static/stories"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Level", name: "level", widget: "number" }
      - { label: "Title Card" name: "title-card", widget: "image" }
      - label: "Section"
        name: "section"
        widget: "list"
        fields:
          - { label: "Media", name: "media", widget: "image" }
          - { label: "Sentence", name: "sentence", widget: "string" }
          - { label: "Word", name: "word", widget: "string", required: false }
